# Generated by Django 2.2.7 on 2019-11-16 21:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AsigPregunta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('pregunta', models.TextField(primary_key=True, serialize=False)),
                ('tipo', models.TextField(blank=True, choices=[('Texto', 'Texto'), ('Opcion multiple', 'Opcion multiple'), ('Verdadero y falso', 'Verdadero y falso')], null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Respuesta',
            fields=[
                ('respuesta', models.TextField(primary_key=True, serialize=False)),
                ('formulario_pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Forms.AsigPregunta')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='Formulario',
            fields=[
                ('nombre', models.TextField(primary_key=True, serialize=False)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('link', models.TextField(blank=True, null=True)),
                ('pregunta', models.ManyToManyField(through='Forms.AsigPregunta', to='Forms.Pregunta')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='users.Profile')),
            ],
        ),
        migrations.AddField(
            model_name='asigpregunta',
            name='formulario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Forms.Formulario'),
        ),
        migrations.AddField(
            model_name='asigpregunta',
            name='pregunta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Forms.Pregunta'),
        ),
    ]
