# Generated by Django 2.2.7 on 2019-11-17 00:05

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Forms', '0002_auto_20191116_1724'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='respuesta',
            name='formulario_pregunta',
        ),
        migrations.AddField(
            model_name='respuesta',
            name='formulario',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, to='Forms.Formulario'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='respuesta',
            name='pregunta',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, to='Forms.Pregunta'),
            preserve_default=False,
        ),
    ]
